id = "luma"
name = "Luma"
version = "0.1.0"
schema_version = 1
description = "Luma language support for Zed"
authors = ["dylanisaiahp"]
repository = "https://github.com/dylanisaiahp/luma"

[grammars.luma]
repository = "https://github.com/dylanisaiahp/luma"
rev = "982cafeb8b7d4d368651482b62858f43ba1158b5"
path = "editor/tree-sitter-luma"
