#![allow(dead_code, unused)]
// luma_runtime.rs — bundled with every luma build output
// This file is generated by luma build and compiled alongside the program.
// Uses only Rust std library — no external crates.

use std::collections::HashMap;
use std::fmt;
use std::io::{self, Read, Write};

#[derive(Debug, Clone, PartialEq)]
pub enum Value {
    Integer(i64),
    Float(f64),
    String(String),
    Char(char),
    Boolean(bool),
    Void,
    Option(Option<Box<Value>>),
    List(Vec<Value>),
    Table(Vec<(Value, Value)>),
    Struct {
        name: String,
        fields: HashMap<String, Value>,
    },
    EnumVariant {
        enum_name: String,
        variant: String,
    },
    EnumVariantData {
        enum_name: String,
        variant: String,
        data: Vec<Value>,
    },
    JsonHandle(String),
    TomlHandle(String),
}

impl fmt::Display for Value {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Value::Integer(n) => write!(f, "{}", n),
            Value::Float(fl) => {
                if fl.abs() > 1_000_000_000_000.0 || (fl.abs() < 0.0001 && *fl != 0.0) {
                    write!(f, "{:e}", fl)
                } else {
                    write!(f, "{}", fl)
                }
            }
            Value::String(s) => write!(f, "{}", s),
            Value::Char(c) => write!(f, "{}", c),
            Value::Boolean(b) => write!(f, "{}", b),
            Value::Void => write!(f, ""),
            Value::Option(Some(inner)) => write!(f, "{}", inner),
            Value::Option(None) => write!(f, ""),
            Value::List(items) => {
                let parts: Vec<String> = items.iter().map(|v| format!("{}", v)).collect();
                write!(f, "({})", parts.join(", "))
            }
            Value::Table(pairs) => {
                let parts: Vec<String> =
                    pairs.iter().map(|(k, v)| format!("{}: {}", k, v)).collect();
                write!(f, "({})", parts.join(", "))
            }
            Value::Struct { name, fields } => {
                let mut pairs: Vec<(&String, &Value)> = fields.iter().collect();
                pairs.sort_by_key(|(k, _)| k.as_str());
                let parts: Vec<String> =
                    pairs.iter().map(|(k, v)| format!("{}: {}", k, v)).collect();
                write!(f, "{}({})", name, parts.join(", "))
            }
            Value::EnumVariant { enum_name, variant } => write!(f, "{}::{}", enum_name, variant),
            Value::EnumVariantData {
                enum_name,
                variant,
                data,
            } => {
                let parts: Vec<String> = data.iter().map(|v| format!("{}", v)).collect();
                write!(f, "{}::{}({})", enum_name, variant, parts.join(", "))
            }
            Value::JsonHandle(s) => write!(f, "json({})", s),
            Value::TomlHandle(s) => write!(f, "toml({})", s),
        }
    }
}

impl Value {
    pub fn type_name(&self) -> &'static str {
        match self {
            Value::Integer(_) => "int",
            Value::Float(_) => "float",
            Value::String(_) => "string",
            Value::Char(_) => "char",
            Value::Boolean(_) => "bool",
            Value::Void => "void",
            Value::Option(_) => "maybe",
            Value::List(_) => "list",
            Value::Table(_) => "table",
            Value::Struct { .. } => "struct",
            Value::EnumVariant { .. } => "enum",
            Value::EnumVariantData { .. } => "enum",
            Value::JsonHandle(_) => "json",
            Value::TomlHandle(_) => "toml",
        }
    }
}

// --- Panic helpers ---

pub fn runtime_error(msg: &str) -> ! {
    eprintln!("[!] Runtime error: {}", msg);
    std::process::exit(1);
}

pub fn runtime_error_with_location(msg: &str, file: &str, line: u32, col: u32) -> ! {
    eprintln!(
        "[!] Runtime error: {} (in {} at line {} col {})",
        msg, file, line, col
    );
    std::process::exit(1);
}

// --- Builtins ---

pub fn luma_print(val: &Value) {
    println!("{}", val);
}

pub fn luma_write(val: &Value) {
    let s = format!("{}", val);
    let processed = s
        .replace("\\r\\n", "\r\n")
        .replace("\\n", "\n")
        .replace("\\r", "\r")
        .replace("\\t", "\t");
    print!("{}", processed);
    io::stdout().flush().unwrap();
}

pub fn luma_read() -> Value {
    io::stdout().flush().unwrap();
    let mut input = String::new();
    io::stdin().read_line(&mut input).unwrap();
    Value::String(input.trim().to_string())
}

pub fn luma_env(key: &Value) -> Value {
    match key {
        Value::String(k) => Value::String(std::env::var(k).unwrap_or_default()),
        _ => runtime_error("env() argument must be a string"),
    }
}

pub fn luma_home() -> Value {
    Value::String(std::env::var("HOME").unwrap_or_default())
}

pub fn luma_time() -> Value {
    use std::time::{SystemTime, UNIX_EPOCH};
    let duration = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default();
    let ms = duration.as_secs() * 1000 + duration.subsec_millis() as u64;
    Value::Integer(ms as i64)
}

pub fn luma_random(min: &Value, max: &Value) -> Value {
    use std::time::{SystemTime, UNIX_EPOCH};
    match (min, max) {
        (Value::Integer(lo), Value::Integer(hi)) => {
            if lo >= hi {
                runtime_error("random(): min must be less than max");
            }
            let seed = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .subsec_nanos() as i64;
            let range = hi - lo + 1;
            Value::Integer(lo + (seed.abs() % range))
        }
        _ => runtime_error("random() arguments must be integers"),
    }
}

pub fn luma_run(parts: &[String]) -> Value {
    let (cmd, args) = match parts.split_first() {
        Some(x) => x,
        None => runtime_error("run() command cannot be empty"),
    };
    let cmd = cmd.trim();
    let args: Vec<String> = args.iter().map(|s| s.trim().to_string()).collect();
    match std::process::Command::new(cmd).args(&args).output() {
        Ok(output) => {
            let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
            let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
            if output.status.success() {
                Value::String(stdout)
            } else {
                let msg = if stderr.is_empty() { stdout } else { stderr };
                eprintln!("[!] run() failed: {}", msg);
                std::process::exit(1);
            }
        }
        Err(e) => {
            eprintln!("[!] run() failed: {}", e);
            std::process::exit(1);
        }
    }
}

// --- Type conversions ---

pub fn luma_int(val: &Value) -> Value {
    match val {
        Value::Integer(n) => Value::Integer(*n),
        Value::Float(f) => Value::Integer(*f as i64),
        Value::Boolean(b) => Value::Integer(if *b { 1 } else { 0 }),
        Value::String(s) => match s.trim().parse::<i64>() {
            Ok(n) => Value::Integer(n),
            Err(_) => runtime_error(&format!("Cannot convert '{}' to integer", s)),
        },
        _ => runtime_error(&format!("Cannot convert {} to integer", val.type_name())),
    }
}

pub fn luma_float(val: &Value) -> Value {
    match val {
        Value::Float(f) => Value::Float(*f),
        Value::Integer(n) => Value::Float(*n as f64),
        Value::Boolean(b) => Value::Float(if *b { 1.0 } else { 0.0 }),
        Value::String(s) => match s.trim().parse::<f64>() {
            Ok(f) => Value::Float(f),
            Err(_) => runtime_error(&format!("Cannot convert '{}' to float", s)),
        },
        _ => runtime_error(&format!("Cannot convert {} to float", val.type_name())),
    }
}

pub fn luma_string(val: &Value) -> Value {
    Value::String(format!("{}", val))
}

// --- Binary operations ---

pub fn luma_add(left: Value, right: Value) -> Value {
    match (left, right) {
        (Value::Integer(l), Value::Integer(r)) => Value::Integer(l + r),
        (Value::Float(l), Value::Float(r)) => Value::Float(l + r),
        (Value::Integer(l), Value::Float(r)) => Value::Float(l as f64 + r),
        (Value::Float(l), Value::Integer(r)) => Value::Float(l + r as f64),
        (Value::String(l), Value::String(r)) => Value::String(l + &r),
        (Value::String(l), Value::Integer(r)) => Value::String(l + &r.to_string()),
        (Value::Integer(l), Value::String(r)) => Value::String(l.to_string() + &r),
        (Value::String(l), Value::Float(r)) => Value::String(l + &r.to_string()),
        (Value::Float(l), Value::String(r)) => Value::String(l.to_string() + &r),
        (l, r) => runtime_error(&format!(
            "Type mismatch in '+': {} and {}",
            l.type_name(),
            r.type_name()
        )),
    }
}

pub fn luma_subtract(left: Value, right: Value) -> Value {
    match (left, right) {
        (Value::Integer(l), Value::Integer(r)) => Value::Integer(l - r),
        (Value::Float(l), Value::Float(r)) => Value::Float(l - r),
        (Value::Integer(l), Value::Float(r)) => Value::Float(l as f64 - r),
        (Value::Float(l), Value::Integer(r)) => Value::Float(l - r as f64),
        (l, r) => runtime_error(&format!(
            "Type mismatch in '-': {} and {}",
            l.type_name(),
            r.type_name()
        )),
    }
}

pub fn luma_multiply(left: Value, right: Value) -> Value {
    match (left, right) {
        (Value::Integer(l), Value::Integer(r)) => Value::Integer(l * r),
        (Value::Float(l), Value::Float(r)) => Value::Float(l * r),
        (Value::Integer(l), Value::Float(r)) => Value::Float(l as f64 * r),
        (Value::Float(l), Value::Integer(r)) => Value::Float(l * r as f64),
        (l, r) => runtime_error(&format!(
            "Type mismatch in '*': {} and {}",
            l.type_name(),
            r.type_name()
        )),
    }
}

pub fn luma_divide(left: Value, right: Value) -> Value {
    match (left, right) {
        (Value::Integer(l), Value::Integer(r)) => {
            if r == 0 {
                runtime_error("Division by zero")
            }
            Value::Integer(l / r)
        }
        (Value::Float(l), Value::Float(r)) => {
            if r == 0.0 {
                runtime_error("Division by zero")
            }
            Value::Float(l / r)
        }
        (Value::Integer(l), Value::Float(r)) => {
            if r == 0.0 {
                runtime_error("Division by zero")
            }
            Value::Float(l as f64 / r)
        }
        (Value::Float(l), Value::Integer(r)) => {
            if r == 0 {
                runtime_error("Division by zero")
            }
            Value::Float(l / r as f64)
        }
        (l, r) => runtime_error(&format!(
            "Type mismatch in '/': {} and {}",
            l.type_name(),
            r.type_name()
        )),
    }
}

pub fn luma_modulo(left: Value, right: Value) -> Value {
    match (left, right) {
        (Value::Integer(l), Value::Integer(r)) => {
            if r == 0 {
                runtime_error("Modulo by zero")
            }
            Value::Integer(l % r)
        }
        (Value::Float(l), Value::Float(r)) => Value::Float(l % r),
        (Value::Integer(l), Value::Float(r)) => Value::Float(l as f64 % r),
        (Value::Float(l), Value::Integer(r)) => Value::Float(l % r as f64),
        (l, r) => runtime_error(&format!(
            "Type mismatch in '%': {} and {}",
            l.type_name(),
            r.type_name()
        )),
    }
}

pub fn luma_compare(left: &Value, right: &Value, op: &str) -> Value {
    let result = match (left, right) {
        (Value::Integer(l), Value::Integer(r)) => match op {
            "==" => l == r,
            "!=" => l != r,
            ">" => l > r,
            "<" => l < r,
            ">=" => l >= r,
            "<=" => l <= r,
            _ => runtime_error(&format!("Cannot use '{}' on floats", op)),
        },
        (Value::Float(l), Value::Float(r)) => match op {
            "==" => l == r,
            "!=" => l != r,
            ">" => l > r,
            "<" => l < r,
            ">=" => l >= r,
            "<=" => l <= r,
            _ => runtime_error(&format!("Cannot use '{}' on floats", op)),
        },
        (Value::Integer(l), Value::Float(r)) => {
            let l = *l as f64;
            match op {
                "==" => l == *r,
                "!=" => l != *r,
                ">" => l > *r,
                "<" => l < *r,
                ">=" => l >= *r,
                "<=" => l <= *r,
                _ => runtime_error(&format!("Cannot use '{}' on integer/float", op)),
            }
        }
        (Value::Float(l), Value::Integer(r)) => {
            let r = *r as f64;
            match op {
                "==" => *l == r,
                "!=" => *l != r,
                ">" => *l > r,
                "<" => *l < r,
                ">=" => *l >= r,
                "<=" => *l <= r,
                _ => runtime_error(&format!("Cannot use '{}' on float/integer", op)),
            }
        }
        (Value::String(l), Value::String(r)) => match op {
            "==" => l == r,
            "!=" => l != r,
            _ => runtime_error(&format!("Cannot use '{}' on strings", op)),
        },
        (Value::Boolean(l), Value::Boolean(r)) => match op {
            "==" => l == r,
            "!=" => l != r,
            _ => runtime_error(&format!("Cannot use '{}' on booleans", op)),
        },
        (Value::Char(l), Value::Char(r)) => match op {
            "==" => l == r,
            "!=" => l != r,
            _ => runtime_error(&format!("Cannot use '{}' on chars", op)),
        },
        (
            Value::EnumVariant {
                enum_name: l_enum,
                variant: l_var,
            },
            Value::EnumVariant {
                enum_name: r_enum,
                variant: r_var,
            },
        ) => match op {
            "==" => l_enum == r_enum && l_var == r_var,
            "!=" => l_enum != r_enum || l_var != r_var,
            _ => runtime_error(&format!("Cannot use '{}' on enums", op)),
        },
        (
            Value::EnumVariantData {
                enum_name: l_enum,
                variant: l_var,
                data: l_data,
            },
            Value::EnumVariantData {
                enum_name: r_enum,
                variant: r_var,
                data: r_data,
            },
        ) => match op {
            "==" => l_enum == r_enum && l_var == r_var && l_data == r_data,
            "!=" => l_enum != r_enum || l_var != r_var || l_data != r_data,
            _ => runtime_error(&format!("Cannot use '{}' on enums", op)),
        },
        _ => runtime_error(&format!(
            "Type mismatch in '{}': {} and {}",
            op,
            left.type_name(),
            right.type_name()
        )),
    };
    Value::Boolean(result)
}

// --- Method dispatch ---

pub fn luma_method(object: Value, method: &str, args: Vec<Value>) -> Value {
    luma_method_with_location(object, method, args, "", 0, 0)
}

pub fn luma_method_with_location(
    object: Value,
    method: &str,
    args: Vec<Value>,
    file: &str,
    line: u32,
    col: u32,
) -> Value {
    match object {
        Value::Integer(n) => int_method(n, method, &args, file, line, col),
        Value::Float(f) => float_method(f, method, &args, file, line, col),
        Value::String(s) => string_method(s, method, &args, file, line, col),
        Value::Char(c) => char_method(c, method, &args, file, line, col),
        Value::Boolean(b) => bool_method(b, method, file, line, col),
        Value::Option(inner) => maybe_method(inner, method, &args, file, line, col),
        Value::List(items) => list_method_with_location(items, method, args, file, line, col),
        Value::Table(pairs) => table_method(pairs, method, args, file, line, col),
        Value::EnumVariant { .. } => runtime_error_with_location(
            &format!("{} has no method '{}'", object.type_name(), method),
            file,
            line,
            col,
        ),
        Value::EnumVariantData { .. } => runtime_error_with_location(
            &format!("{} has no method '{}'", object.type_name(), method),
            file,
            line,
            col,
        ),
        Value::Void => runtime_error_with_location(
            &format!("{} has no method '{}'", object.type_name(), method),
            file,
            line,
            col,
        ),
        Value::Struct { name, fields } => struct_method_with_location(
            name,
            fields,
            method,
            &args,
            file,
            line,
            col,
        ),
        Value::JsonHandle(s) => luma_json_method(&s, method, &args),
        Value::TomlHandle(s) => luma_toml_method(&s, method, &args),
    }
}

fn list_method_with_location(
    items: Vec<Value>,
    method: &str,
    args: Vec<Value>,
    file: &str,
    line: u32,
    col: u32,
) -> Value {
    match method {
        "len" => Value::Integer(items.len() as i64),
        "exists" => Value::Boolean(!items.is_empty()),
        "get" => match args.first() {
            Some(Value::Integer(i)) => {
                let idx = *i as usize;
                match items.get(idx) {
                    Some(v) => v.clone(),
                    None => runtime_error_with_location(
                        &format!("list index {} out of bounds (len {})", i, items.len()),
                        file,
                        line,
                        col,
                    ),
                }
            }
            _ => runtime_error_with_location(
                "list.get() takes one integer argument",
                file,
                line,
                col,
            ),
        },
        "contains" => {
            let target = args.first().unwrap_or_else(|| {
                runtime_error_with_location("list.contains() takes one argument", file, line, col)
            });
            Value::Boolean(items.contains(target))
        }
        "where" => match args.first() {
            Some(target) => {
                let idx = items.iter().position(|v| v == target);
                Value::Integer(idx.map(|i| i as i64).unwrap_or(-1))
            }
            _ => runtime_error_with_location("list.where() takes one argument", file, line, col),
        },
        "add" => {
            let val = args.into_iter().next().unwrap_or_else(|| {
                runtime_error_with_location("list.add() takes one argument", file, line, col)
            });
            let mut new_items = items;
            new_items.push(val);
            Value::List(new_items)
        }
        "remove" => {
            let first_arg = args.into_iter().next();
            match first_arg {
                Some(Value::Integer(i)) => {
                    let idx = i as usize;
                    if idx >= items.len() {
                        runtime_error_with_location(
                            &format!("list index {} out of bounds (len {})", i, items.len()),
                            file,
                            line,
                            col,
                        );
                    }
                    let mut new_items = items;
                    new_items.remove(idx);
                    Value::List(new_items)
                }
                _ => runtime_error_with_location(
                    "list.remove() takes one integer index argument",
                    file,
                    line,
                    col,
                ),
            }
        }
        "reverse" => {
            let mut new_items = items;
            new_items.reverse();
            Value::List(new_items)
        }
        "sort" => {
            let mut new_items = items;
            new_items.sort_by(|a, b| match (a, b) {
                (Value::Integer(x), Value::Integer(y)) => x.cmp(y),
                (Value::Float(x), Value::Float(y)) => {
                    x.partial_cmp(y).unwrap_or(std::cmp::Ordering::Equal)
                }
                (Value::String(x), Value::String(y)) => x.cmp(y),
                _ => std::cmp::Ordering::Equal,
            });
            Value::List(new_items)
        }
        "first" => match items.first() {
            Some(v) => v.clone(),
            None => {
                runtime_error_with_location("list.first() called on empty list", file, line, col)
            }
        },
        "last" => match items.last() {
            Some(v) => v.clone(),
            None => {
                runtime_error_with_location("list.last() called on empty list", file, line, col)
            }
        },
        "merge" => {
            let first_arg = args.into_iter().next();
            let glue = match first_arg {
                Some(Value::String(s)) => s,
                Some(Value::Char(c)) => c.to_string(),
                None => String::new(),
                _ => runtime_error_with_location(
                    "list.merge() takes a string separator argument",
                    file,
                    line,
                    col,
                ),
            };
            let parts: Vec<String> = items.iter().map(|v| format!("{}", v)).collect();
            Value::String(parts.join(&glue))
        }
        _ => runtime_error_with_location(
            &format!("list has no method '{}'", method),
            file,
            line,
            col,
        ),
    }
}

fn int_method(n: i64, method: &str, args: &[Value], file: &str, line: u32, col: u32) -> Value {
    match method {
        "abs" => Value::Integer(n.abs()),
        "to_float" => Value::Float(n as f64),
        "to_string" => Value::String(n.to_string()),
        "exists" => Value::Boolean(n != 0),
        "pow" => match args.first() {
            Some(Value::Integer(exp)) if *exp >= 0 => Value::Integer(n.pow(*exp as u32)),
            _ => runtime_error_with_location(
                "int.pow() takes one non-negative integer argument",
                file,
                line,
                col,
            ),
        },
        _ => {
            runtime_error_with_location(&format!("int has no method '{}'", method), file, line, col)
        }
    }
}

fn float_method(f: f64, method: &str, args: &[Value], file: &str, line: u32, col: u32) -> Value {
    match method {
        "abs" => Value::Float(f.abs()),
        "floor" => Value::Integer(f.floor() as i64),
        "ceil" => Value::Integer(f.ceil() as i64),
        "round" => Value::Integer(f.round() as i64),
        "to_int" => Value::Integer(f as i64),
        "to_string" => Value::String(f.to_string()),
        "exists" => Value::Boolean(f != 0.0),
        _ => runtime_error_with_location(
            &format!("float has no method '{}'", method),
            file,
            line,
            col,
        ),
    }
}

fn string_method(
    s: String,
    method: &str,
    args: &[Value],
    file: &str,
    line: u32,
    col: u32,
) -> Value {
    match method {
        "len" => Value::Integer(s.len() as i64),
        "upper" => Value::String(s.to_uppercase()),
        "lower" => Value::String(s.to_lowercase()),
        "trim" => Value::String(s.trim().to_string()),
        "reverse" => Value::String(s.chars().rev().collect()),
        "chars" => Value::List(s.chars().map(|c| Value::String(c.to_string())).collect()),
        "exists" => Value::Boolean(!s.is_empty()),
        "contains" => match args.first() {
            Some(Value::String(sub)) => Value::Boolean(s.contains(sub.as_str())),
            Some(Value::Char(c)) => Value::Boolean(s.contains(*c)),
            _ => runtime_error_with_location(
                "contains() takes one string or char argument",
                file,
                line,
                col,
            ),
        },
        "starts_with" => match args.first() {
            Some(Value::String(p)) => Value::Boolean(s.starts_with(p.as_str())),
            Some(Value::Char(c)) => Value::Boolean(s.starts_with(*c)),
            _ => runtime_error_with_location(
                "starts_with() takes one string or char argument",
                file,
                line,
                col,
            ),
        },
        "ends_with" => match args.first() {
            Some(Value::String(p)) => Value::Boolean(s.ends_with(p.as_str())),
            Some(Value::Char(c)) => Value::Boolean(s.ends_with(*c)),
            _ => runtime_error_with_location(
                "ends_with() takes one string or char argument",
                file,
                line,
                col,
            ),
        },
        "repeat" => match args.first() {
            Some(Value::Integer(n)) if *n >= 0 => Value::String(s.repeat(*n as usize)),
            _ => runtime_error_with_location(
                "repeat() takes one non-negative integer argument",
                file,
                line,
                col,
            ),
        },
        "replace" => match (args.first(), args.get(1)) {
            (Some(Value::String(from)), Some(Value::String(to))) => {
                Value::String(s.replace(from.as_str(), to.as_str()))
            }
            _ => {
                runtime_error_with_location("replace() takes two string arguments", file, line, col)
            }
        },
        "split" => match args.first() {
            Some(Value::String(delim)) => Value::List(
                s.split(delim.as_str())
                    .map(|p| Value::String(p.to_string()))
                    .collect(),
            ),
            Some(Value::Char(c)) => {
                Value::List(s.split(*c).map(|p| Value::String(p.to_string())).collect())
            }
            None => Value::List(
                s.split_whitespace()
                    .map(|p| Value::String(p.to_string()))
                    .collect(),
            ),
            _ => runtime_error_with_location(
                "split() takes one string or char argument",
                file,
                line,
                col,
            ),
        },
        "first" => match s.chars().next() {
            Some(c) => Value::Option(Some(Box::new(Value::Char(c)))),
            None => Value::Option(None),
        },
        "last" => match s.chars().next_back() {
            Some(c) => Value::Option(Some(Box::new(Value::Char(c)))),
            None => Value::Option(None),
        },
        "as" => match args.first() {
            Some(Value::String(target)) => match target.as_str() {
                "int" => match s.trim().parse::<i64>() {
                    Ok(n) => Value::Option(Some(Box::new(Value::Integer(n)))),
                    Err(_) => Value::Option(None),
                },
                "float" => match s.trim().parse::<f64>() {
                    Ok(f) => Value::Option(Some(Box::new(Value::Float(f)))),
                    Err(_) => Value::Option(None),
                },
                "bool" => match s.trim() {
                    "true" => Value::Option(Some(Box::new(Value::Boolean(true)))),
                    "false" => Value::Option(Some(Box::new(Value::Boolean(false)))),
                    _ => Value::Option(None),
                },
                "char" => {
                    if s.chars().count() == 1 {
                        Value::Option(Some(Box::new(Value::Char(s.chars().next().unwrap()))))
                    } else {
                        Value::Option(None)
                    }
                }
                _ => runtime_error_with_location(
                    &format!("as() unknown target type '{}'", target),
                    file,
                    line,
                    col,
                ),
            },
            _ => runtime_error_with_location("as() takes a type argument", file, line, col),
        },
        "concat" => {
            // Calculate total length needed for single allocation
            let mut total_len = s.len();
            for arg in args {
                match arg {
                    Value::String(a) => total_len += a.len(),
                    Value::Char(c) => total_len += c.len_utf8(),
                    _ => {
                        return runtime_error_with_location(
                            "concat() takes only string or char arguments",
                            file,
                            line,
                            col,
                        )
                    }
                }
            }

            // Allocate once with exact capacity
            let mut result = String::with_capacity(total_len);
            result.push_str(&s);

            // Copy all parts in a single pass
            for arg in args {
                match arg {
                    Value::String(a) => result.push_str(a),
                    Value::Char(c) => result.push(*c),
                    _ => unreachable!(), // Already checked above
                }
            }

            Value::String(result)
        }
        "hash" => {
            // FNV-1a hash (fast, non-cryptographic)
            const FNV_OFFSET_BASIS: u64 = 0xcbf29ce484222325;
            const FNV_PRIME: u64 = 0x00000100000001b3;
            
            let mut hash = FNV_OFFSET_BASIS;
            for byte in s.bytes() {
                hash ^= byte as u64;
                hash = hash.wrapping_mul(FNV_PRIME);
            }
            
            // Return as hex string
            Value::String(format!("{:x}", hash))
        }
        _ => runtime_error_with_location(
            &format!("string has no method '{}'", method),
            file,
            line,
            col,
        ),
    }
}

fn char_method(c: char, method: &str, args: &[Value], file: &str, line: u32, col: u32) -> Value {
    match method {
        "exists" => Value::Boolean(true),
        "to_string" => Value::String(c.to_string()),
        "to_int" => Value::Integer(c as i64),
        _ => string_method(c.to_string(), method, args, file, line, col),
    }
}

fn bool_method(b: bool, method: &str, file: &str, line: u32, col: u32) -> Value {
    match method {
        "to_string" => Value::String(b.to_string()),
        "exists" => Value::Boolean(b),
        _ => runtime_error_with_location(
            &format!("bool has no method '{}'", method),
            file,
            line,
            col,
        ),
    }
}

fn maybe_method(
    inner: Option<Box<Value>>,
    method: &str,
    args: &[Value],
    file: &str,
    line: u32,
    col: u32,
) -> Value {
    match method {
        "exists" => Value::Boolean(inner.is_some()),
        "or" => match inner {
            Some(v) => *v,
            None => match args.first() {
                Some(v) => v.clone(),
                None => runtime_error_with_location(
                    "maybe.or() requires a fallback value",
                    file,
                    line,
                    col,
                ),
            },
        },
        _ => match inner {
            Some(v) => luma_method_with_location(*v, method, args.to_vec(), file, line, col),
            None => {
                if method == "add" || method == "push" {
                    list_method_with_location(vec![], method, args.to_vec(), file, line, col)
                } else if method == "len" {
                    Value::Integer(0)
                } else if method == "get" {
                    runtime_error_with_location("Cannot get from empty list", file, line, col)
                } else if method == "contains" || method == "where" {
                    Value::Boolean(false)
                } else if method == "exists" {
                    Value::Boolean(false)
                } else {
                    runtime_error_with_location(
                        &format!("Cannot call '{}' on empty maybe — use .or() first", method),
                        file,
                        line,
                        col,
                    )
                }
            }
        },
    }
}

fn table_method(
    pairs: Vec<(Value, Value)>,
    method: &str,
    args: Vec<Value>,
    file: &str,
    line: u32,
    col: u32,
) -> Value {
    match method {
        "len" => Value::Integer(pairs.len() as i64),
        "exists" => Value::Boolean(!pairs.is_empty()),
        "has" => {
            let key = args.first().unwrap_or_else(|| {
                runtime_error_with_location("table.has() takes one argument", file, line, col)
            });
            Value::Boolean(pairs.iter().any(|(k, _)| k == key))
        }
        "get" => {
            let key = args.first().unwrap_or_else(|| {
                runtime_error_with_location("table.get() takes one argument", file, line, col)
            });
            match pairs.iter().find(|(k, _)| k == key) {
                Some((_, v)) => v.clone(),
                None => runtime_error_with_location("table key not found", file, line, col),
            }
        }
        "set" => {
            if args.len() != 2 {
                runtime_error_with_location(
                    "table.set() takes two arguments (key, value)",
                    file,
                    line,
                    col,
                );
            }
            let mut args_iter = args.into_iter();
            let key = args_iter.next().unwrap();
            let val = args_iter.next().unwrap();
            let mut new_pairs = pairs;
            if let Some(entry) = new_pairs.iter_mut().find(|(k, _)| k == &key) {
                entry.1 = val;
            } else {
                new_pairs.push((key, val));
            }
            Value::Table(new_pairs)
        }
        "remove" => {
            let key = args.into_iter().next().unwrap_or_else(|| {
                runtime_error_with_location("table.remove() takes one argument", file, line, col)
            });
            let mut new_pairs = pairs;
            new_pairs.retain(|(k, _)| k != &key);
            Value::Table(new_pairs)
        }
        "keys" => Value::List(pairs.iter().map(|(k, _)| k.clone()).collect()),
        "values" => Value::List(pairs.iter().map(|(_, v)| v.clone()).collect()),
        _ => runtime_error_with_location(
            &format!("table has no method '{}'", method),
            file,
            line,
            col,
        ),
    }
}

// --- Struct method dispatch ---

fn struct_method(
    name: String,
    fields: HashMap<String, Value>,
    method: &str,
    args: &[Value],
) -> Value {
    struct_method_with_location(name, fields, method, args, "", 0, 0)
}

fn struct_method_with_location(
    name: String,
    fields: HashMap<String, Value>,
    method: &str,
    args: &[Value],
    file: &str,
    line: u32,
    col: u32,
) -> Value {
    match (name.as_str(), method) {
        (_, "sum") => {
            let vals: Vec<&Value> = fields.values().collect();
            if vals.len() == 2 {
                if let (Value::Integer(a), Value::Integer(b)) = (vals[0], vals[1]) {
                    return Value::Integer(a + b);
                }
            }
            runtime_error_with_location(
                &format!("{}.sum() requires exactly two integer fields", name),
                file,
                line,
                col,
            )
        }
        (_, "greet") => {
            if let Some(Value::String(n)) = fields.get("name") {
                return Value::String(format!("Hi, I am {}", n));
            }
            runtime_error_with_location(
                &format!("{}.greet() requires a 'name' field", name),
                file,
                line,
                col,
            )
        }
        (_, "next") => {
            if let Some(Value::Integer(v)) = fields.get("value") {
                if let Some(Value::Integer(step)) = args.first() {
                    return Value::Integer(v + step);
                }
            }
            runtime_error_with_location(
                &format!(
                    "{}.next() requires integer value field and step argument",
                    name
                ),
                file,
                line,
                col,
            )
        }
        _ => runtime_error_with_location(
            &format!("{} has no method '{}'", name, method),
            file,
            line,
            col,
        ),
    }
}

// --- File handle ---

pub fn luma_file_method(path: &str, method: &str, args: &[Value]) -> Value {
    match method {
        "read" => match std::fs::read_to_string(path) {
            Ok(s) => Value::String(s),
            Err(e) => runtime_error(&format!("file(\"{}\").read() failed: {}", path, e)),
        },
        "write" => {
            let content = match args.first() {
                Some(Value::String(s)) => s.clone(),
                Some(v) => format!("{}", v),
                None => String::new(),
            };
            if let Some(parent) = std::path::Path::new(path).parent() {
                if !parent.as_os_str().is_empty() {
                    let _ = std::fs::create_dir_all(parent);
                }
            }
            match std::fs::write(path, &content) {
                Ok(_) => Value::Void,
                Err(e) => runtime_error(&format!("file(\"{}\").write() failed: {}", path, e)),
            }
        }
        "append" => {
            use std::io::Write;
            let content = match args.first() {
                Some(Value::String(s)) => s.clone(),
                Some(v) => format!("{}", v),
                None => String::new(),
            };
            if let Some(parent) = std::path::Path::new(path).parent() {
                if !parent.as_os_str().is_empty() {
                    let _ = std::fs::create_dir_all(parent);
                }
            }
            match std::fs::OpenOptions::new()
                .create(true)
                .append(true)
                .open(path)
            {
                Ok(mut f) => match f.write_all(content.as_bytes()) {
                    Ok(_) => Value::Void,
                    Err(e) => runtime_error(&format!("file(\"{}\").append() failed: {}", path, e)),
                },
                Err(e) => runtime_error(&format!(
                    "file(\"{}\").append() failed to open: {}",
                    path, e
                )),
            }
        }
        "exists" => Value::Boolean(std::path::Path::new(path).exists()),
        "list" => {
            let filter = match args.first() {
                Some(Value::String(s)) => s.clone(),
                None => String::new(),
                _ => runtime_error("file.list() takes an optional string filter"),
            };
            let dir = std::path::Path::new(path);
            let entries = match std::fs::read_dir(dir) {
                Ok(e) => e,
                Err(e) => runtime_error(&format!("file(\"{}\").list() failed: {}", path, e)),
            };
            let mut results: Vec<Value> = Vec::new();
            for entry in entries.flatten() {
                let entry_path = entry.path();
                let name = entry_path
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("")
                    .to_string();
                let is_dir = entry_path.is_dir();
                let matches = match filter.as_str() {
                    "" => true,
                    "." => !is_dir,
                    "/" => is_dir,
                    ext if ext.starts_with('.') => !is_dir && name.ends_with(ext),
                    _ => false,
                };
                if matches {
                    results.push(Value::String(name));
                }
            }
            Value::List(results)
        }
        _ => runtime_error(&format!("file() has no method '{}'", method)),
    }
}

// --- Fetch handle ---
// fetch() is not available in compiled binaries — use luma run for network programs.

pub fn luma_fetch_method(url: &str, method: &str, _args: &[Value]) -> Value {
    runtime_error(&format!(
        "fetch() is not available in compiled binaries — use luma run for network requests (url: {}, method: {})",
        url, method
    ))
}

// --- Args (replaces input().args()) ---

pub fn luma_args() -> Value {
    let args: Vec<Value> = std::env::args().skip(1).map(|s| Value::String(s)).collect();
    Value::List(args)
}

// --- Read N bytes ---

pub fn luma_read_n(n: &Value) -> Value {
    let n = match n {
        Value::Integer(n) => *n as usize,
        _ => runtime_error("read_n() argument must be an integer"),
    };

    io::stdout().flush().unwrap();

    if n == 0 {
        return Value::String(String::new());
    }

    let mut buffer = vec![0u8; n];
    let mut stdin = io::stdin();
    let mut total_read = 0;

    while total_read < n {
        match stdin.read(&mut buffer[total_read..]) {
            Ok(0) => break,
            Ok(bytes) => total_read += bytes,
            Err(e) => runtime_error(&format!("read_n() failed: {}", e)),
        }
    }

    buffer.truncate(total_read);
    Value::String(String::from_utf8_lossy(&buffer).to_string())
}

// --- JSON ---

// Simple JSON encoder/parser using only std library

pub fn luma_json(val: &Value) -> Value {
    match val {
        Value::String(s) => Value::JsonHandle(s.clone()),
        Value::Table(pairs) => {
            let encoded = encode_json_table(pairs);
            Value::String(encoded)
        }
        _ => runtime_error("json() argument must be a string or table"),
    }
}

fn encode_json_table(pairs: &[(Value, Value)]) -> String {
    let mut parts = Vec::new();
    for (k, v) in pairs {
        if let Value::String(key) = k {
            let encoded_value = encode_json_value(v);
            parts.push(format!("\"{}\": {}", escape_json(key), encoded_value));
        }
    }
    format!("{{\n  {}\n}}", parts.join(",\n  "))
}

fn encode_json_value(value: &Value) -> String {
    match value {
        Value::Integer(n) => n.to_string(),
        Value::Float(f) => f.to_string(),
        Value::String(s) => format!("\"{}\"", escape_json(s)),
        Value::Char(c) => format!("\"{}\"", escape_json(&c.to_string())),
        Value::Boolean(b) => b.to_string(),
        Value::Void => "null".to_string(),
        Value::Option(None) => "null".to_string(),
        Value::Option(Some(v)) => encode_json_value(v),
        Value::List(items) => {
            let parts: Vec<String> = items.iter().map(encode_json_value).collect();
            format!("[{}]", parts.join(", "))
        }
        Value::Table(pairs) => encode_json_table(pairs),
        _ => "\"<handle>\"".to_string(),
    }
}

fn escape_json(s: &str) -> String {
    let mut result = String::new();
    for c in s.chars() {
        match c {
            '"' => result.push_str("\\\""),
            '\\' => result.push_str("\\\\"),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            _ => result.push(c),
        }
    }
    result
}

pub fn luma_json_method(json_str: &str, method: &str, args: &[Value]) -> Value {
    match method {
        "parse" => match parse_json(json_str) {
            Ok(table) => Value::Table(table),
            Err(e) => runtime_error(&format!("json.parse() failed: {}", e)),
        },
        "encode" => {
            let table = match args.first() {
                Some(Value::Table(t)) => t.clone(),
                _ => runtime_error("json.encode() requires a table argument"),
            };
            Value::String(encode_json_table(&table))
        }
        _ => runtime_error(&format!("json() has no method '{}'", method)),
    }
}

fn parse_json(s: &str) -> Result<Vec<(Value, Value)>, String> {
    let chars: Vec<char> = s.chars().collect();
    let mut pos = 0;

    skip_whitespace(&chars, &mut pos);

    if pos >= chars.len() || chars[pos] != '{' {
        return Err("expected '{'".to_string());
    }
    pos += 1;

    skip_whitespace(&chars, &mut pos);

    let mut result = Vec::new();

    if pos < chars.len() && chars[pos] == '}' {
        return Ok(result);
    }

    loop {
        skip_whitespace(&chars, &mut pos);

        if pos >= chars.len() {
            return Err("unexpected end of input".to_string());
        }

        if chars[pos] != '"' {
            return Err("expected property name".to_string());
        }

        let key = parse_string(&chars, &mut pos)?;

        skip_whitespace(&chars, &mut pos);

        if pos >= chars.len() || chars[pos] != ':' {
            return Err("expected ':'".to_string());
        }
        pos += 1;

        skip_whitespace(&chars, &mut pos);

        let value = parse_json_value(&chars, &mut pos)?;

        flatten_json_value(&key, value, &mut result);

        skip_whitespace(&chars, &mut pos);

        if pos >= chars.len() {
            return Err("unexpected end of input".to_string());
        }

        if chars[pos] == '}' {
            pos += 1;
            break;
        }

        if chars[pos] != ',' {
            return Err("expected ',' or '}'".to_string());
        }
        pos += 1;
    }

    Ok(result)
}

fn flatten_json_value(prefix: &str, value: Value, result: &mut Vec<(Value, Value)>) {
    match value {
        Value::String(s) => result.push((Value::String(prefix.to_string()), Value::String(s))),
        Value::List(list) => result.push((Value::String(prefix.to_string()), Value::List(list))),
        Value::Table(pairs) => {
            for (k, v) in pairs {
                if let Value::String(key) = k {
                    let new_prefix = if prefix.is_empty() {
                        key.clone()
                    } else {
                        format!("{}.{}", prefix, key)
                    };
                    flatten_json_value(&new_prefix, v, result);
                }
            }
        }
        _ => {}
    }
}

fn skip_whitespace(chars: &[char], pos: &mut usize) {
    while *pos < chars.len() {
        let c = chars[*pos];
        if c == ' ' || c == '\t' || c == '\n' || c == '\r' {
            *pos += 1;
        } else {
            break;
        }
    }
}

fn parse_string(chars: &[char], pos: &mut usize) -> Result<String, String> {
    if *pos >= chars.len() || chars[*pos] != '"' {
        return Err("expected '\"'".to_string());
    }
    *pos += 1;

    let mut result = String::new();

    while *pos < chars.len() {
        let c = chars[*pos];
        if c == '"' {
            *pos += 1;
            return Ok(result);
        }
        if c == '\\' {
            *pos += 1;
            if *pos >= chars.len() {
                return Err("unexpected end after \\".to_string());
            }
            match chars[*pos] {
                'n' => result.push('\n'),
                'r' => result.push('\r'),
                't' => result.push('\t'),
                '"' => result.push('"'),
                '\\' => result.push('\\'),
                _ => result.push(chars[*pos]),
            }
        } else {
            result.push(c);
        }
        *pos += 1;
    }

    Err("unterminated string".to_string())
}

fn parse_json_value(chars: &[char], pos: &mut usize) -> Result<Value, String> {
    skip_whitespace(chars, pos);

    if *pos >= chars.len() {
        return Err("unexpected end of input".to_string());
    }

    let c = chars[*pos];

    if c == '"' {
        let s = parse_string(chars, pos)?;
        return Ok(Value::String(s));
    }

    if c == 't' || c == 'f' {
        let remaining: String = chars[*pos..].iter().take(5).collect();
        if remaining.starts_with("true") {
            *pos += 4;
            return Ok(Value::String("true".to_string()));
        }
        if remaining.starts_with("false") {
            *pos += 5;
            return Ok(Value::String("false".to_string()));
        }
    }

    if c == 'n' {
        let remaining: String = chars[*pos..].iter().take(4).collect();
        if remaining.starts_with("null") {
            *pos += 4;
            return Ok(Value::String("null".to_string()));
        }
    }

    if c == '[' {
        *pos += 1;
        let mut items = Vec::new();
        skip_whitespace(chars, pos);
        if *pos < chars.len() && chars[*pos] == ']' {
            *pos += 1;
            return Ok(Value::List(items));
        }
        loop {
            let item = parse_json_value(chars, pos)?;
            items.push(item);
            skip_whitespace(chars, pos);
            if *pos >= chars.len() {
                return Err("unterminated array".to_string());
            }
            if chars[*pos] == ']' {
                *pos += 1;
                break;
            }
            if chars[*pos] != ',' {
                return Err("expected ',' in array".to_string());
            }
            *pos += 1;
            skip_whitespace(chars, pos);
        }
        return Ok(Value::List(items));
    }

    if c == '{' {
        *pos += 1;
        skip_whitespace(chars, pos);
        if *pos < chars.len() && chars[*pos] == '}' {
            *pos += 1;
            return Ok(Value::Table(Vec::new()));
        }
        let mut pairs = Vec::new();
        loop {
            skip_whitespace(chars, pos);
            if *pos >= chars.len() || chars[*pos] != '"' {
                return Err("expected property name".to_string());
            }
            let key = parse_string(chars, pos)?;
            skip_whitespace(chars, pos);
            if *pos >= chars.len() || chars[*pos] != ':' {
                return Err("expected ':'".to_string());
            }
            *pos += 1;
            skip_whitespace(chars, pos);
            let value = parse_json_value(chars, pos)?;
            pairs.push((Value::String(key), value));
            skip_whitespace(chars, pos);
            if *pos >= chars.len() {
                return Err("unterminated object".to_string());
            }
            if chars[*pos] == '}' {
                *pos += 1;
                break;
            }
            if chars[*pos] != ',' {
                return Err("expected ',' in object".to_string());
            }
            *pos += 1;
        }
        return Ok(Value::Table(pairs));
    }

    let mut num_str = String::new();
    while *pos < chars.len() {
        let c = chars[*pos];
        if c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == ',' || c == '}' || c == ']' {
            break;
        }
        num_str.push(c);
        *pos += 1;
    }

    if num_str.contains('.') {
        match num_str.parse::<f64>() {
            Ok(f) => return Ok(Value::String(f.to_string())),
            Err(_) => return Err(format!("invalid float: {}", num_str)),
        }
    }

    Ok(Value::String(num_str))
}

// --- TOML ---

pub fn luma_toml(val: &Value) -> Value {
    match val {
        Value::String(s) => Value::TomlHandle(s.clone()),
        Value::Table(pairs) => {
            let encoded = encode_toml_table(pairs);
            Value::String(encoded)
        }
        _ => runtime_error("toml() argument must be a string or table"),
    }
}

fn encode_toml_table(pairs: &[(Value, Value)]) -> String {
    let mut lines = Vec::new();
    for (k, v) in pairs {
        if let Value::String(key) = k {
            lines.push(format!("{} = {}", key, encode_toml_value(v)));
        }
    }
    lines.join("\n")
}

fn encode_toml_value(value: &Value) -> String {
    match value {
        Value::Integer(n) => n.to_string(),
        Value::Float(f) => f.to_string(),
        Value::String(s) => format!("\"{}\"", escape_toml_string(s)),
        Value::Char(c) => format!("\"{}\"", escape_toml_string(&c.to_string())),
        Value::Boolean(b) => b.to_string(),
        Value::Void => "void".to_string(),
        Value::Option(None) => "null".to_string(),
        Value::Option(Some(v)) => encode_toml_value(v),
        Value::List(items) => {
            let parts: Vec<String> = items.iter().map(|v| encode_toml_value(v)).collect();
            format!("[{}]", parts.join(", "))
        }
        Value::Table(_) => "[table]".to_string(),
        _ => "<handle>".to_string(),
    }
}

fn escape_toml_string(s: &str) -> String {
    let mut result = String::new();
    for c in s.chars() {
        match c {
            '"' => result.push_str("\\\""),
            '\\' => result.push_str("\\\\"),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            _ => result.push(c),
        }
    }
    result
}

pub fn luma_toml_method(toml_str: &str, method: &str, args: &[Value]) -> Value {
    match method {
        "parse" => match parse_toml(toml_str) {
            Ok(table) => Value::Table(table),
            Err(e) => runtime_error(&format!("toml.parse() failed: {}", e)),
        },
        "encode" => {
            let table = match args.first() {
                Some(Value::Table(t)) => t.clone(),
                _ => runtime_error("toml.encode() requires a table argument"),
            };
            Value::String(encode_toml_table(&table))
        }
        _ => runtime_error(&format!("toml() has no method '{}'", method)),
    }
}

fn parse_toml(s: &str) -> Result<Vec<(Value, Value)>, String> {
    let lines: Vec<&str> = s.lines().collect();
    let mut result = Vec::new();
    let mut current_table = String::new();

    for line in lines {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        if trimmed.starts_with('[') {
            if !trimmed.ends_with(']') {
                return Err("invalid table header".to_string());
            }
            let inner = &trimmed[1..trimmed.len() - 1];
            current_table = if current_table.is_empty() {
                inner.to_string()
            } else {
                format!("{}.{}", current_table, inner)
            };
            continue;
        }

        if let Some(eq_pos) = trimmed.find('=') {
            let key = trimmed[..eq_pos].trim();
            let value = trimmed[eq_pos + 1..].trim();

            let full_key = if current_table.is_empty() {
                key.to_string()
            } else {
                format!("{}.{}", current_table, key)
            };

            let parsed_value = parse_toml_value(value)?;
            result.push((Value::String(full_key), parsed_value));
        }
    }

    Ok(result)
}

fn parse_toml_value(s: &str) -> Result<Value, String> {
    let s = s.trim();

    if s.starts_with('"') && s.ends_with('"') && s.len() >= 2 {
        let inner = &s[1..s.len() - 1];
        let mut result = String::new();
        let mut chars = inner.chars().peekable();
        while let Some(c) = chars.next() {
            if c == '\\' {
                match chars.next() {
                    Some('n') => result.push('\n'),
                    Some('r') => result.push('\r'),
                    Some('t') => result.push('\t'),
                    Some('"') => result.push('"'),
                    Some('\\') => result.push('\\'),
                    Some(other) => result.push(other),
                    None => return Err("unexpected end after \\".to_string()),
                }
            } else {
                result.push(c);
            }
        }
        return Ok(Value::String(result));
    }

    if s == "true" {
        return Ok(Value::Boolean(true));
    }
    if s == "false" {
        return Ok(Value::Boolean(false));
    }

    if let Ok(n) = s.parse::<i64>() {
        return Ok(Value::Integer(n));
    }

    if let Ok(f) = s.parse::<f64>() {
        return Ok(Value::Float(f));
    }

    Ok(Value::String(s.to_string()))
}
