#![allow(dead_code, unused)]
// luma_runtime.rs — bundled with every luma build output
// This file is generated by luma build and compiled alongside the program.

use std::collections::HashMap;
use std::fmt;
use std::io::{self, Write};

#[derive(Debug, Clone, PartialEq)]
pub enum Value {
    Integer(i64),
    Float(f64),
    String(String),
    Char(char),
    Boolean(bool),
    Void,
    Maybe(Option<Box<Value>>),
    List(Vec<Value>),
    Table(Vec<(Value, Value)>),
    Struct {
        name: String,
        fields: HashMap<String, Value>,
    },
}

impl fmt::Display for Value {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Value::Integer(n) => write!(f, "{}", n),
            Value::Float(fl) => {
                if fl.abs() > 1_000_000_000_000.0 || (fl.abs() < 0.0001 && *fl != 0.0) {
                    write!(f, "{:e}", fl)
                } else {
                    write!(f, "{}", fl)
                }
            }
            Value::String(s) => write!(f, "{}", s),
            Value::Char(c) => write!(f, "{}", c),
            Value::Boolean(b) => write!(f, "{}", b),
            Value::Void => write!(f, ""),
            Value::Maybe(Some(inner)) => write!(f, "{}", inner),
            Value::Maybe(None) => write!(f, ""),
            Value::List(items) => {
                let parts: Vec<String> = items.iter().map(|v| format!("{}", v)).collect();
                write!(f, "({})", parts.join(", "))
            }
            Value::Table(pairs) => {
                let parts: Vec<String> =
                    pairs.iter().map(|(k, v)| format!("{}: {}", k, v)).collect();
                write!(f, "({})", parts.join(", "))
            }
            Value::Struct { name, fields } => {
                let mut pairs: Vec<(&String, &Value)> = fields.iter().collect();
                pairs.sort_by_key(|(k, _)| k.as_str());
                let parts: Vec<String> =
                    pairs.iter().map(|(k, v)| format!("{}: {}", k, v)).collect();
                write!(f, "{}({})", name, parts.join(", "))
            }
        }
    }
}

impl Value {
    pub fn type_name(&self) -> &'static str {
        match self {
            Value::Integer(_) => "int",
            Value::Float(_) => "float",
            Value::String(_) => "string",
            Value::Char(_) => "char",
            Value::Boolean(_) => "bool",
            Value::Void => "void",
            Value::Maybe(_) => "maybe",
            Value::List(_) => "list",
            Value::Table(_) => "table",
            Value::Struct { .. } => "struct",
        }
    }
}

// --- Panic helpers ---

pub fn runtime_error(msg: &str) -> ! {
    eprintln!("[!] Runtime error: {}", msg);
    std::process::exit(1);
}

// --- Builtins ---

pub fn luma_print(val: &Value) {
    println!("{}", val);
}

pub fn luma_write(val: &Value) {
    print!("{}", val);
    io::stdout().flush().unwrap();
}

pub fn luma_read() -> Value {
    io::stdout().flush().unwrap();
    let mut input = String::new();
    io::stdin().read_line(&mut input).unwrap();
    Value::String(input.trim().to_string())
}

pub fn luma_random(min: &Value, max: &Value) -> Value {
    use std::time::{SystemTime, UNIX_EPOCH};
    match (min, max) {
        (Value::Integer(lo), Value::Integer(hi)) => {
            if lo >= hi {
                runtime_error("random(): min must be less than max");
            }
            let seed = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .subsec_nanos() as i64;
            let range = hi - lo + 1;
            Value::Integer(lo + (seed.abs() % range))
        }
        _ => runtime_error("random() arguments must be integers"),
    }
}

pub fn luma_run(parts: &[String]) -> Value {
    let (cmd, args) = match parts.split_first() {
        Some(x) => x,
        None => runtime_error("run() command cannot be empty"),
    };
    match std::process::Command::new(cmd).args(args).output() {
        Ok(output) => {
            let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
            let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
            if output.status.success() {
                Value::String(stdout)
            } else {
                let msg = if stderr.is_empty() { stdout } else { stderr };
                eprintln!("[!] run() failed: {}", msg);
                std::process::exit(1);
            }
        }
        Err(e) => {
            eprintln!("[!] run() failed: {}", e);
            std::process::exit(1);
        }
    }
}

// --- Type conversions ---

pub fn luma_int(val: &Value) -> Value {
    match val {
        Value::Integer(n) => Value::Integer(*n),
        Value::Float(f) => Value::Integer(*f as i64),
        Value::Boolean(b) => Value::Integer(if *b { 1 } else { 0 }),
        Value::String(s) => match s.trim().parse::<i64>() {
            Ok(n) => Value::Integer(n),
            Err(_) => runtime_error(&format!("Cannot convert '{}' to integer", s)),
        },
        _ => runtime_error(&format!("Cannot convert {} to integer", val.type_name())),
    }
}

pub fn luma_float(val: &Value) -> Value {
    match val {
        Value::Float(f) => Value::Float(*f),
        Value::Integer(n) => Value::Float(*n as f64),
        Value::Boolean(b) => Value::Float(if *b { 1.0 } else { 0.0 }),
        Value::String(s) => match s.trim().parse::<f64>() {
            Ok(f) => Value::Float(f),
            Err(_) => runtime_error(&format!("Cannot convert '{}' to float", s)),
        },
        _ => runtime_error(&format!("Cannot convert {} to float", val.type_name())),
    }
}

pub fn luma_string(val: &Value) -> Value {
    Value::String(format!("{}", val))
}

// --- Binary operations ---

pub fn luma_add(left: Value, right: Value) -> Value {
    match (left, right) {
        (Value::Integer(l), Value::Integer(r)) => Value::Integer(l + r),
        (Value::Float(l), Value::Float(r)) => Value::Float(l + r),
        (Value::Integer(l), Value::Float(r)) => Value::Float(l as f64 + r),
        (Value::Float(l), Value::Integer(r)) => Value::Float(l + r as f64),
        (Value::String(l), Value::String(r)) => Value::String(l + &r),
        (Value::String(l), Value::Integer(r)) => Value::String(l + &r.to_string()),
        (Value::Integer(l), Value::String(r)) => Value::String(l.to_string() + &r),
        (Value::String(l), Value::Float(r)) => Value::String(l + &r.to_string()),
        (Value::Float(l), Value::String(r)) => Value::String(l.to_string() + &r),
        (l, r) => runtime_error(&format!(
            "Type mismatch in '+': {} and {}",
            l.type_name(),
            r.type_name()
        )),
    }
}

pub fn luma_subtract(left: Value, right: Value) -> Value {
    match (left, right) {
        (Value::Integer(l), Value::Integer(r)) => Value::Integer(l - r),
        (Value::Float(l), Value::Float(r)) => Value::Float(l - r),
        (Value::Integer(l), Value::Float(r)) => Value::Float(l as f64 - r),
        (Value::Float(l), Value::Integer(r)) => Value::Float(l - r as f64),
        (l, r) => runtime_error(&format!(
            "Type mismatch in '-': {} and {}",
            l.type_name(),
            r.type_name()
        )),
    }
}

pub fn luma_multiply(left: Value, right: Value) -> Value {
    match (left, right) {
        (Value::Integer(l), Value::Integer(r)) => Value::Integer(l * r),
        (Value::Float(l), Value::Float(r)) => Value::Float(l * r),
        (Value::Integer(l), Value::Float(r)) => Value::Float(l as f64 * r),
        (Value::Float(l), Value::Integer(r)) => Value::Float(l * r as f64),
        (l, r) => runtime_error(&format!(
            "Type mismatch in '*': {} and {}",
            l.type_name(),
            r.type_name()
        )),
    }
}

pub fn luma_divide(left: Value, right: Value) -> Value {
    match (left, right) {
        (Value::Integer(l), Value::Integer(r)) => {
            if r == 0 {
                runtime_error("Division by zero")
            }
            Value::Integer(l / r)
        }
        (Value::Float(l), Value::Float(r)) => {
            if r == 0.0 {
                runtime_error("Division by zero")
            }
            Value::Float(l / r)
        }
        (Value::Integer(l), Value::Float(r)) => {
            if r == 0.0 {
                runtime_error("Division by zero")
            }
            Value::Float(l as f64 / r)
        }
        (Value::Float(l), Value::Integer(r)) => {
            if r == 0 {
                runtime_error("Division by zero")
            }
            Value::Float(l / r as f64)
        }
        (l, r) => runtime_error(&format!(
            "Type mismatch in '/': {} and {}",
            l.type_name(),
            r.type_name()
        )),
    }
}

pub fn luma_modulo(left: Value, right: Value) -> Value {
    match (left, right) {
        (Value::Integer(l), Value::Integer(r)) => {
            if r == 0 {
                runtime_error("Modulo by zero")
            }
            Value::Integer(l % r)
        }
        (Value::Float(l), Value::Float(r)) => Value::Float(l % r),
        (Value::Integer(l), Value::Float(r)) => Value::Float(l as f64 % r),
        (Value::Float(l), Value::Integer(r)) => Value::Float(l % r as f64),
        (l, r) => runtime_error(&format!(
            "Type mismatch in '%': {} and {}",
            l.type_name(),
            r.type_name()
        )),
    }
}

pub fn luma_compare(left: &Value, right: &Value, op: &str) -> Value {
    let result = match (left, right) {
        (Value::Integer(l), Value::Integer(r)) => match op {
            "==" => l == r,
            "!=" => l != r,
            ">" => l > r,
            "<" => l < r,
            ">=" => l >= r,
            "<=" => l <= r,
            _ => unreachable!(),
        },
        (Value::Float(l), Value::Float(r)) => match op {
            "==" => l == r,
            "!=" => l != r,
            ">" => l > r,
            "<" => l < r,
            ">=" => l >= r,
            "<=" => l <= r,
            _ => unreachable!(),
        },
        (Value::Integer(l), Value::Float(r)) => {
            let l = *l as f64;
            match op {
                "==" => l == *r,
                "!=" => l != *r,
                ">" => l > *r,
                "<" => l < *r,
                ">=" => l >= *r,
                "<=" => l <= *r,
                _ => unreachable!(),
            }
        }
        (Value::Float(l), Value::Integer(r)) => {
            let r = *r as f64;
            match op {
                "==" => *l == r,
                "!=" => *l != r,
                ">" => *l > r,
                "<" => *l < r,
                ">=" => *l >= r,
                "<=" => *l <= r,
                _ => unreachable!(),
            }
        }
        (Value::String(l), Value::String(r)) => match op {
            "==" => l == r,
            "!=" => l != r,
            _ => runtime_error(&format!("Cannot use '{}' on strings", op)),
        },
        (Value::Boolean(l), Value::Boolean(r)) => match op {
            "==" => l == r,
            "!=" => l != r,
            _ => runtime_error(&format!("Cannot use '{}' on booleans", op)),
        },
        (Value::Char(l), Value::Char(r)) => match op {
            "==" => l == r,
            "!=" => l != r,
            _ => runtime_error(&format!("Cannot use '{}' on chars", op)),
        },
        _ => runtime_error(&format!(
            "Type mismatch in '{}': {} and {}",
            op,
            left.type_name(),
            right.type_name()
        )),
    };
    Value::Boolean(result)
}

// --- Method dispatch ---

pub fn luma_method(object: Value, method: &str, args: Vec<Value>) -> Value {
    match &object {
        Value::Integer(n) => int_method(*n, method, &args),
        Value::Float(f) => float_method(*f, method, &args),
        Value::String(s) => string_method(s.clone(), method, &args),
        Value::Char(c) => char_method(*c, method, &args),
        Value::Boolean(b) => bool_method(*b, method),
        Value::Maybe(inner) => maybe_method(inner.clone(), method, &args),
        Value::List(items) => list_method(items.clone(), method, &args),
        Value::Table(pairs) => table_method(pairs.clone(), method, &args),
        _ => runtime_error(&format!(
            "{} has no method '{}'",
            object.type_name(),
            method
        )),
    }
}

fn int_method(n: i64, method: &str, args: &[Value]) -> Value {
    match method {
        "abs" => Value::Integer(n.abs()),
        "to_float" => Value::Float(n as f64),
        "to_string" => Value::String(n.to_string()),
        "exists" => Value::Boolean(n != 0),
        "pow" => match args.first() {
            Some(Value::Integer(exp)) if *exp >= 0 => Value::Integer(n.pow(*exp as u32)),
            _ => runtime_error("int.pow() takes one non-negative integer argument"),
        },
        _ => runtime_error(&format!("int has no method '{}'", method)),
    }
}

fn float_method(f: f64, method: &str, _args: &[Value]) -> Value {
    match method {
        "abs" => Value::Float(f.abs()),
        "floor" => Value::Integer(f.floor() as i64),
        "ceil" => Value::Integer(f.ceil() as i64),
        "round" => Value::Integer(f.round() as i64),
        "to_int" => Value::Integer(f as i64),
        "to_string" => Value::String(f.to_string()),
        "exists" => Value::Boolean(f != 0.0),
        _ => runtime_error(&format!("float has no method '{}'", method)),
    }
}

fn string_method(s: String, method: &str, args: &[Value]) -> Value {
    match method {
        "len" => Value::Integer(s.chars().count() as i64),
        "upper" => Value::String(s.to_uppercase()),
        "lower" => Value::String(s.to_lowercase()),
        "trim" => Value::String(s.trim().to_string()),
        "reverse" => Value::String(s.chars().rev().collect()),
        "chars" => Value::List(s.chars().map(Value::Char).collect()),
        "exists" => Value::Boolean(!s.is_empty()),
        "contains" => match args.first() {
            Some(Value::String(sub)) => Value::Boolean(s.contains(sub.as_str())),
            Some(Value::Char(c)) => Value::Boolean(s.contains(*c)),
            _ => runtime_error("contains() takes one string or char argument"),
        },
        "starts_with" => match args.first() {
            Some(Value::String(p)) => Value::Boolean(s.starts_with(p.as_str())),
            Some(Value::Char(c)) => Value::Boolean(s.starts_with(*c)),
            _ => runtime_error("starts_with() takes one string or char argument"),
        },
        "ends_with" => match args.first() {
            Some(Value::String(p)) => Value::Boolean(s.ends_with(p.as_str())),
            Some(Value::Char(c)) => Value::Boolean(s.ends_with(*c)),
            _ => runtime_error("ends_with() takes one string or char argument"),
        },
        "repeat" => match args.first() {
            Some(Value::Integer(n)) if *n >= 0 => Value::String(s.repeat(*n as usize)),
            _ => runtime_error("repeat() takes one non-negative integer argument"),
        },
        "replace" => match (args.first(), args.get(1)) {
            (Some(Value::String(from)), Some(Value::String(to))) => {
                Value::String(s.replace(from.as_str(), to.as_str()))
            }
            _ => runtime_error("replace() takes two string arguments"),
        },
        "split" => match args.first() {
            Some(Value::String(delim)) => Value::List(
                s.split(delim.as_str())
                    .map(|p| Value::String(p.to_string()))
                    .collect(),
            ),
            Some(Value::Char(c)) => {
                Value::List(s.split(*c).map(|p| Value::String(p.to_string())).collect())
            }
            None => Value::List(
                s.split_whitespace()
                    .map(|p| Value::String(p.to_string()))
                    .collect(),
            ),
            _ => runtime_error("split() takes one string or char argument"),
        },
        "first" => match s.chars().next() {
            Some(c) => Value::Maybe(Some(Box::new(Value::Char(c)))),
            None => Value::Maybe(None),
        },
        "last" => match s.chars().next_back() {
            Some(c) => Value::Maybe(Some(Box::new(Value::Char(c)))),
            None => Value::Maybe(None),
        },
        "as" => match args.first() {
            Some(Value::String(target)) => match target.as_str() {
                "int" => match s.trim().parse::<i64>() {
                    Ok(n) => Value::Maybe(Some(Box::new(Value::Integer(n)))),
                    Err(_) => Value::Maybe(None),
                },
                "float" => match s.trim().parse::<f64>() {
                    Ok(f) => Value::Maybe(Some(Box::new(Value::Float(f)))),
                    Err(_) => Value::Maybe(None),
                },
                "bool" => match s.trim() {
                    "true" => Value::Maybe(Some(Box::new(Value::Boolean(true)))),
                    "false" => Value::Maybe(Some(Box::new(Value::Boolean(false)))),
                    _ => Value::Maybe(None),
                },
                "char" => {
                    if s.chars().count() == 1 {
                        Value::Maybe(Some(Box::new(Value::Char(s.chars().next().unwrap()))))
                    } else {
                        Value::Maybe(None)
                    }
                }
                _ => runtime_error(&format!("as() unknown target type '{}'", target)),
            },
            _ => runtime_error("as() takes a type argument"),
        },
        _ => runtime_error(&format!("string has no method '{}'", method)),
    }
}

fn char_method(c: char, method: &str, args: &[Value]) -> Value {
    match method {
        "exists" => Value::Boolean(true),
        "to_string" => Value::String(c.to_string()),
        "to_int" => Value::Integer(c as i64),
        _ => string_method(c.to_string(), method, args),
    }
}

fn bool_method(b: bool, method: &str) -> Value {
    match method {
        "to_string" => Value::String(b.to_string()),
        "exists" => Value::Boolean(b),
        _ => runtime_error(&format!("bool has no method '{}'", method)),
    }
}

fn maybe_method(inner: Option<Box<Value>>, method: &str, args: &[Value]) -> Value {
    match method {
        "exists" => Value::Boolean(inner.is_some()),
        "or" => match inner {
            Some(v) => *v,
            None => match args.first() {
                Some(v) => v.clone(),
                None => runtime_error("maybe.or() requires a fallback value"),
            },
        },
        _ => match inner {
            Some(v) => luma_method(*v, method, args.to_vec()),
            None => runtime_error(&format!(
                "Cannot call '{}' on empty maybe — use .or() first",
                method
            )),
        },
    }
}

fn list_method(items: Vec<Value>, method: &str, args: &[Value]) -> Value {
    match method {
        "len" => Value::Integer(items.len() as i64),
        "exists" => Value::Boolean(!items.is_empty()),
        "get" => match args.first() {
            Some(Value::Integer(i)) => {
                let idx = *i as usize;
                match items.get(idx) {
                    Some(v) => v.clone(),
                    None => runtime_error(&format!(
                        "list index {} out of bounds (len {})",
                        i,
                        items.len()
                    )),
                }
            }
            _ => runtime_error("list.get() takes one integer argument"),
        },
        "contains" => {
            let target = args
                .first()
                .unwrap_or_else(|| runtime_error("list.contains() takes one argument"));
            Value::Boolean(items.contains(target))
        }
        "where" => match args.first() {
            Some(target) => {
                let idx = items.iter().position(|v| v == target);
                Value::Integer(idx.map(|i| i as i64).unwrap_or(-1))
            }
            _ => runtime_error("list.where() takes one argument"),
        },
        "add" => {
            let val = args
                .first()
                .unwrap_or_else(|| runtime_error("list.add() takes one argument"));
            let mut new_items = items;
            new_items.push(val.clone());
            Value::List(new_items)
        }
        "remove" => match args.first() {
            Some(Value::Integer(i)) => {
                let idx = *i as usize;
                if idx >= items.len() {
                    runtime_error(&format!(
                        "list index {} out of bounds (len {})",
                        i,
                        items.len()
                    ));
                }
                let mut new_items = items;
                new_items.remove(idx);
                Value::List(new_items)
            }
            _ => runtime_error("list.remove() takes one integer index argument"),
        },
        "reverse" => {
            let mut new_items = items;
            new_items.reverse();
            Value::List(new_items)
        }
        "sort" => {
            let mut new_items = items;
            new_items.sort_by(|a, b| match (a, b) {
                (Value::Integer(x), Value::Integer(y)) => x.cmp(y),
                (Value::Float(x), Value::Float(y)) => {
                    x.partial_cmp(y).unwrap_or(std::cmp::Ordering::Equal)
                }
                (Value::String(x), Value::String(y)) => x.cmp(y),
                _ => std::cmp::Ordering::Equal,
            });
            Value::List(new_items)
        }
        "first" => match items.first() {
            Some(v) => v.clone(),
            None => runtime_error("list.first() called on empty list"),
        },
        "last" => match items.last() {
            Some(v) => v.clone(),
            None => runtime_error("list.last() called on empty list"),
        },
        "merge" => {
            let glue = match args.first() {
                Some(Value::String(s)) => s.clone(),
                Some(Value::Char(c)) => c.to_string(),
                None => String::new(),
                _ => runtime_error("list.merge() takes a string separator argument"),
            };
            let parts: Vec<String> = items.iter().map(|v| format!("{}", v)).collect();
            Value::String(parts.join(&glue))
        }
        _ => runtime_error(&format!("list has no method '{}'", method)),
    }
}

fn table_method(pairs: Vec<(Value, Value)>, method: &str, args: &[Value]) -> Value {
    match method {
        "len" => Value::Integer(pairs.len() as i64),
        "exists" => Value::Boolean(!pairs.is_empty()),
        "has" => {
            let key = args
                .first()
                .unwrap_or_else(|| runtime_error("table.has() takes one argument"));
            Value::Boolean(pairs.iter().any(|(k, _)| k == key))
        }
        "get" => {
            let key = args
                .first()
                .unwrap_or_else(|| runtime_error("table.get() takes one argument"));
            match pairs.iter().find(|(k, _)| k == key) {
                Some((_, v)) => v.clone(),
                None => runtime_error("table key not found"),
            }
        }
        "set" => {
            if args.len() != 2 {
                runtime_error("table.set() takes two arguments (key, value)");
            }
            let key = args[0].clone();
            let val = args[1].clone();
            let mut new_pairs = pairs;
            if let Some(entry) = new_pairs.iter_mut().find(|(k, _)| k == &key) {
                entry.1 = val;
            } else {
                new_pairs.push((key, val));
            }
            Value::Table(new_pairs)
        }
        "remove" => {
            let key = args
                .first()
                .unwrap_or_else(|| runtime_error("table.remove() takes one argument"));
            let mut new_pairs = pairs;
            new_pairs.retain(|(k, _)| k != key);
            Value::Table(new_pairs)
        }
        "keys" => Value::List(pairs.iter().map(|(k, _)| k.clone()).collect()),
        "values" => Value::List(pairs.iter().map(|(_, v)| v.clone()).collect()),
        _ => runtime_error(&format!("table has no method '{}'", method)),
    }
}

// --- File handle ---

pub fn luma_file_method(path: &str, method: &str, args: &[Value]) -> Value {
    match method {
        "read" => match std::fs::read_to_string(path) {
            Ok(s) => Value::String(s),
            Err(e) => runtime_error(&format!("file(\"{}\").read() failed: {}", path, e)),
        },
        "write" => {
            let content = match args.first() {
                Some(Value::String(s)) => s.clone(),
                Some(v) => format!("{}", v),
                None => String::new(),
            };
            if let Some(parent) = std::path::Path::new(path).parent() {
                if !parent.as_os_str().is_empty() {
                    let _ = std::fs::create_dir_all(parent);
                }
            }
            match std::fs::write(path, &content) {
                Ok(_) => Value::Void,
                Err(e) => runtime_error(&format!("file(\"{}\").write() failed: {}", path, e)),
            }
        }
        "append" => {
            use std::io::Write;
            let content = match args.first() {
                Some(Value::String(s)) => s.clone(),
                Some(v) => format!("{}", v),
                None => String::new(),
            };
            if let Some(parent) = std::path::Path::new(path).parent() {
                if !parent.as_os_str().is_empty() {
                    let _ = std::fs::create_dir_all(parent);
                }
            }
            match std::fs::OpenOptions::new()
                .create(true)
                .append(true)
                .open(path)
            {
                Ok(mut f) => match f.write_all(content.as_bytes()) {
                    Ok(_) => Value::Void,
                    Err(e) => runtime_error(&format!("file(\"{}\").append() failed: {}", path, e)),
                },
                Err(e) => runtime_error(&format!(
                    "file(\"{}\").append() failed to open: {}",
                    path, e
                )),
            }
        }
        "exists" => Value::Boolean(std::path::Path::new(path).exists()),
        "list" => {
            let filter = match args.first() {
                Some(Value::String(s)) => s.clone(),
                None => String::new(),
                _ => runtime_error("file.list() takes an optional string filter"),
            };
            let dir = std::path::Path::new(path);
            let entries = match std::fs::read_dir(dir) {
                Ok(e) => e,
                Err(e) => runtime_error(&format!("file(\"{}\").list() failed: {}", path, e)),
            };
            let mut results: Vec<Value> = Vec::new();
            for entry in entries.flatten() {
                let entry_path = entry.path();
                let name = entry_path
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("")
                    .to_string();
                let is_dir = entry_path.is_dir();
                let matches = match filter.as_str() {
                    "" => true,
                    "." => !is_dir,
                    "/" => is_dir,
                    ext if ext.starts_with('.') => !is_dir && name.ends_with(ext),
                    _ => false,
                };
                if matches {
                    results.push(Value::String(name));
                }
            }
            Value::List(results)
        }
        _ => runtime_error(&format!("file() has no method '{}'", method)),
    }
}

// --- Fetch handle ---
// fetch() is not available in compiled binaries — use luma run for network programs.

pub fn luma_fetch_method(url: &str, method: &str, _args: &[Value]) -> Value {
    runtime_error(&format!(
        "fetch() is not available in compiled binaries — use luma run for network requests (url: {}, method: {})",
        url, method
    ))
}

// --- Input handle ---

pub fn luma_input_method(method: &str) -> Value {
    let raw: Vec<String> = std::env::args().skip(1).collect();
    match method {
        "args" => Value::List(
            raw.iter()
                .filter(|a| !a.starts_with('-'))
                .map(|a| Value::String(a.clone()))
                .collect(),
        ),
        "flags" => {
            let mut flags: Vec<Value> = Vec::new();
            let mut i = 0;
            while i < raw.len() {
                let arg = &raw[i];
                if arg.starts_with('-') {
                    let next_is_value =
                        raw.get(i + 1).map(|n| !n.starts_with('-')).unwrap_or(false);
                    if !next_is_value {
                        flags.push(Value::String(arg.trim_start_matches('-').to_string()));
                    }
                    i += if next_is_value { 2 } else { 1 };
                } else {
                    i += 1;
                }
            }
            Value::List(flags)
        }
        "options" => {
            let mut opts: Vec<(Value, Value)> = Vec::new();
            let mut i = 0;
            while i < raw.len() {
                let arg = &raw[i];
                if arg.starts_with('-') {
                    if let Some(next) = raw.get(i + 1) {
                        if !next.starts_with('-') {
                            let key = arg.trim_start_matches('-').to_string();
                            opts.push((Value::String(key), Value::String(next.clone())));
                            i += 2;
                            continue;
                        }
                    }
                }
                i += 1;
            }
            Value::Table(opts)
        }
        _ => runtime_error(&format!("input() has no method '{}'", method)),
    }
}
